Controllers/ContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SnackMVC.Controllers
{
    
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SnackMVC.Models;
using SnackMVC.Repositories.Interfaces;
using SnackMVC.ViewModels;

namespace SnackMVC.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly ISnackRepository _snackRepository;
        private readonly ShopCart _shopCart;

        public ShopCartController(ISnackRepository snackRepository, ShopCart shopCart)
        {
            _snackRepository = snackRepository;
            _shopCart = shopCart;
        }

        public IActionResult Index()
        {
            var itens = _shopCart.GetShopCartItems();
            _shopCart.ShopCartItens = itens;

            var shopCartVM = new ShopCartViewModel
            {
                ShopCart = _shopCart,
                ShopCartTotal = _shopCart.GetCartTotalBuy()
            };

            return View(shopCartVM);
        }

        [Authorize]
        public IActionResult AddItemtoCart(int snackId)
        {
            var selectedSnack = _snackRepository.Snacks.FirstOrDefault(s => s.SnackId == snackId);

            if(selectedSnack != null)
            {
                _shopCart.AddToCart(selectedSnack);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult RemoveItemFromCart(int snackId)
        {
            var selectedSnack = _snackRepository.Snacks.FirstOrDefault(s => s.SnackId == snackId);

            if (selectedSnack != null)
            {
                _shopCart.RemoveFromCart(selectedSnack);
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/SnackController.cs
using Microsoft.AspNetCore.Mvc;
using SnackMVC.Models;
using SnackMVC.Repositories.Interfaces;
using SnackMVC.ViewModels;

namespace SnackMVC.Controllers
{
    public class SnackController : Controller
    {
        private readonly ISnackRepository _snackrepository;

        public SnackController(ISnackRepository snackrepository)
        {
            _snackrepository = snackrepository;
        }

        public IActionResult List(string category)
        {
            IEnumerable<Snack> snacks;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                snacks = _snackrepository.Snacks.OrderBy(l => l.SnackId);
                currentCategory = "All Snacks";
            }
            else
            {
                    snacks = _snackrepository.Snacks
                    .Where(s => s.Category.CategoryName
                    .Equals(category))
                    .OrderBy(c => c.Name);

                currentCategory = category;
            }

            var snackListViewModel = new SnackListViewModel
            {
                Snacks = snacks,
                CurrentCategory = currentCategory
            };

            return View(snackListViewModel);
        }

        public IActionResult Details(int snackId)
        {
            var snack = _snackrepository.Snacks.FirstOrDefault(s => s.SnackId == snackId);
            return View(snack);
        }

        public ViewResult Search (string searchString)
        {
            IEnumerable<Snack> snacks;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                snacks = _snackrepository.Snacks.OrderBy(s => s.SnackId);
                currentCategory = "All snacks";
            }
            else
            {
                snacks = _snackrepository.Snacks.Where(s => s.Name.ToLower().Contains(searchString.ToLower()));

                if (snacks.Any())
                    currentCategory = "Snacks";
                else
                    currentCategory = "Snacks not found";
            }
            return View("~/Views/Snack/List.cshtml", new SnackListViewModel
            {
                Snacks = snacks,
                CurrentCategory = currentCategory
            });
        }
    }
}

Views/Shared/_Carousel.cshtml
<div id="carouselSnack" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/images/carousel11.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/carousel12.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/carousel13.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselSnack" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselSnack" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SnackMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SnackMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SnackMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>     
                        @*<li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Snack" asp-action="List">Snacks</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-ligth" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li> 
                        <li>
                            @await Component.InvokeAsync("ShopCartResume")
                        </li>
                        <li>
                            @await Component.InvokeAsync("CategoryMenu")
                        </li>
                        <form class="navbar-form navbar-right" asp-controller="Snack" asp-action="Search" method="get">
                      <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search product" name="searchString" value="@ViewData["searchString"]">
                      </div>
                    </form>
                    @await Html.PartialAsync("_LoginPartial")
                    @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-ligth" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SnackMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SnacksResume.cshtml
@model Snack

<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImageUrl" class="img-fluid"></p>
    <h3>Preço : @Model.Price.ToString("c")</h3>

    <h4>
    <a asp-controller="Snack" asp-action="Details" 
    asp-route-snackId="@Model.SnackId">@Model.Name</a>
    </h4>

    <p>@Model.ShortDescription</p>
      <div>
        <p class="btn btn-group align-content-lg-end" >
            <a asp-controller="Snack" asp-action="List" 
               class="btn btn-outline-info">See all snacks</a>
            <a class="btn btn-primary" id="cartButton" asp-controller="ShopCart" 
            asp-action="AddItemtoCart" asp-route-snackId="@Model.SnackId"> 
            Add @Model.Name to cart
            </a>
         </p>
    </div>

</div>