Areas/Admin/Controllers/AdminOrdersController.cs
using SnackMVC.Context;
using SnackMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;
using SnackMVC.ViewModels;

namespace LanchesMac.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminOrdersController : Controller
    {
        private readonly AppDbContext _context;

        public AdminOrdersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminPedidos
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Orders.ToListAsync());
        //}

        public async Task<IActionResult> Index(string filter, int pageindex = 1, string sort = "Name")
        {
            var result = _context.Orders.AsNoTracking()
                                        .AsQueryable();

            if (!string.IsNullOrWhiteSpace(filter))
            {
                result = result.Where(p => p.Name.Contains(filter));
            }

            var model = await PagingList.CreateAsync(result, 5, pageindex, sort, "Name");
            model.RouteValue = new RouteValueDictionary { { "filter ", filter } };
            return View(model);
        }

        // GET: Admin/AdminPedidos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Orders
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,Name,LastName,Adress1,Adress2,ZIP,State,City,Telephone,Email,OrderSent,OrderDelivered")] Order pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Orders.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Admin/AdminPedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,Name,LastName,Adress1,Adress2,ZIP,State,City,Telephone,Email,OrderSent,OrderDelivered")] Order pedido)
        {
            if (id != pedido.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Orders
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Admin/AdminPedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(pedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }

        public IActionResult SnackOrder(int? id)
        {
            var order = _context.Orders
                                .Include(or => or.OrderItens)
                                .ThenInclude(s => s.Snack)
                                .FirstOrDefault(o => o.OrderId == id);

            if (order == null)
            {
                Response.StatusCode = 404;
                return View("OrderNotFound", id.Value);
            }

            OrderSnackViewModel orderSnack = new OrderSnackViewModel()
            {
                Order = order,
                OrderDetails = order.OrderItens
            };

            return View(orderSnack);
        }
    }
}

Areas/Admin/Views/AdminOrders/Create.cshtml
@model SnackMVC.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress1" class="control-label"></label>
                <input asp-for="Adress1" class="form-control" />
                <span asp-validation-for="Adress1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress2" class="control-label"></label>
                <input asp-for="Adress2" class="form-control" />
                <span asp-validation-for="Adress2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZIP" class="control-label"></label>
                <input asp-for="ZIP" class="form-control" />
                <span asp-validation-for="ZIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderSent" class="control-label"></label>
                <input asp-for="OrderSent" class="form-control" />
                <span asp-validation-for="OrderSent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDelivered" class="control-label"></label>
                <input asp-for="OrderDelivered" class="form-control" />
                <span asp-validation-for="OrderDelivered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminOrders/Delete.cshtml
@model SnackMVC.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZIP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZIP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderSent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderSent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDelivered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDelivered)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/AdminOrders/Details.cshtml
@model SnackMVC.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZIP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZIP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderSent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderSent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDelivered)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDelivered)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.OrderId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminOrders/Edit.cshtml
@model SnackMVC.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress1" class="control-label"></label>
                <input asp-for="Adress1" class="form-control" />
                <span asp-validation-for="Adress1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress2" class="control-label"></label>
                <input asp-for="Adress2" class="form-control" />
                <span asp-validation-for="Adress2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZIP" class="control-label"></label>
                <input asp-for="ZIP" class="form-control" />
                <span asp-validation-for="ZIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" />
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderSent" class="control-label"></label>
                <input asp-for="OrderSent" class="form-control" />
                <span asp-validation-for="OrderSent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDelivered" class="control-label"></label>
                <input asp-for="OrderDelivered" class="form-control" />
                <span asp-validation-for="OrderDelivered" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminOrders/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<SnackMVC.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h3>Index</h3>

<form method="get" class="form-inline">
    <input name="filter" class="form-control" placeholder="filter"
            value="@Model.RouteValue["Filter"]"/>
    <button type="submit" class="btn btn-info">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
    </button>
</form>

Total Orders : @Model.TotalRecordCount
<div>
    <vc:pager paging-list="@Model"></vc:pager>
</div>

<p>
    <a asp-action="Create">Create New Order</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adress1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adress2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZIP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telephone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderSent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDelivered)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZIP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderSent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDelivered)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a> |
                <a asp-action="SnackOrder" asp-route-id="@item.OrderId">Order Itens</a>
            </td>
        </tr>
}
    </tbody>
</table>

Areas/Admin/Views/AdminOrders/OrderNotFound.cshtml
@model int

@{
    ViewData["Title"] = "404 Not Found";
}

<div class="alert alert-danger mt-1 mb-1">
    <h1>Erro 404 - Not Found </h1>
    <hr />
    <h2>
        Order with id = @Model not found 
    </h2>
</div>

<a asp-action="Index" asp-controller="AdminOrders" class="btn btn-outline-success">
    <h2>Return to Order List</h2>
</a>

Areas/Admin/Views/AdminOrders/SnackOrder.cshtml
@model SnackMVC.ViewModels.OrderSnackViewModel

@{
    ViewData["Title"] = "SnackOrder";
    decimal totalOrder = 0;
}

<h1>Order Snacks</h1>
<hr />

<h3>Order  :  @Html.DisplayFor(model => @Model.Order.OrderId)</h3>
<h3>Client :  @Html.DisplayFor(model => @Model.Order.Name)</h3>
<h3>Date    :  @Html.DisplayFor(model => @Model.Order.OrderSent)</h3>
<h3>Delivery :  @Html.DisplayFor(model => @Model.Order.OrderDelivered)</h3>

<table class="table">
    @foreach (var item in @Model.Order.OrderItens)
    {
        totalOrder += (@item.Snack.Price * @item.Amount);
        <tr>
            <td align="right">
                <h3>@Html.DisplayFor(modelItem => item.Snack.Name)</h3>
            </td>
            <td align="right">
                <img src="@item.Snack.ImageUrl" class="img-fluid" height="100" width="100">
            </td>
            <td align="right">
                <h3>@string.Format("{0:C}", item.Snack.Price)</h3>
            </td>
            <td align="right">
                <h3>(@Html.DisplayFor(modelItem => item.Amount))</h3>
            </td>
        </tr>
    }
    <tr>
            <td colspan="2">&nbsp;</td>
            <td align="right">
                <h3>Total Order : @string.Format("{0:C}", @totalOrder)</h3>
            </td>
    </tr>
</table>
<a asp-action="Index" class="btn btn-outline-info">Return</a>